### ISSUE TITLE
[BUG] Entity isn't loading on HA dashboard  - Cannot read properties of undefined (reading 'state')

### ISSUE THREAD

**Issue by rpanachi** [wilsto/pool-monitor-card#33]
**Describe the bug**
The entity isn't loading on dashboard

**To Reproduce**
Console logs:
```
 POOL-MONITORING-CARD  1.5.1 
auto-entities.js?hacstag=1677445841121:172 AUTO-ENTITIES 1.12.1 IS INSTALLED
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
apexcharts-card.js?hacstag=331701152204:835  APEXCHARTS-CARD  v2.0.4 
card-555679fd.js:507  FRIGATE-HASS-CARD  Version 5.2.0 
2pool_monitor_card.js?hacstag=640244449151:455 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'state')
    at PoolMonitorCard.calculateData (pool_monitor_card.js?hacstag=640244449151:455:57)
    at PoolMonitorCard.processData (pool_monitor_card.js?hacstag=640244449151:407:31)
    at PoolMonitorCard.render (pool_monitor_card.js?hacstag=640244449151:252:23)
    at PoolMonitorCard.update (lit-element.ts:160:24)
    at PoolMonitorCard.performUpdate (reactive-element.ts:1329:14)
    at PoolMonitorCard.scheduleUpdate (reactive-element.ts:1261:17)
    at PoolMonitorCard._$Ej (reactive-element.ts:1233:25)
calculateData @ pool_monitor_card.js?hacstag=640244449151:455
processData @ pool_monitor_card.js?hacstag=640244449151:407
render @ pool_monitor_card.js?hacstag=640244449151:252
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
(anonymous) @ hui-view.ts:153
value @ hui-view.ts:151
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hui-root.ts:607
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ partial-panel-resolver.ts:101
value @ hass-router-page.ts:91
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
j @ lit-html.ts:1883
_$AI @ lit-html.ts:1825
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:95
(anonymous) @ connection-mixin.ts:227
s @ store.js:19
(anonymous) @ entities.js:74
e.subscribeMessage.type @ entities.js:76
(anonymous) @ connection.js:23
_handleMessage @ connection.js:15
Show 5 more frames
Show less
log-message.ts:37 
        
        
       GET https://homeassistant.local/unknown/src/lit-element.ts 404 (Not Found)
(anonymous) @ stacktrace-gps.js:37
r @ stacktrace-gps.js:23
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then (async)
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:37
(anonymous) @ logging-mixin.ts:66
Show 13 more frames
Show less
log-message.ts:37         
        
       GET https://homeassistant.local/unknown/src/reactive-element.ts 404 (Not Found)
```

**Expected behavior**
Entity load as expected. It was working days ago

**Screenshots**

**Environment (please complete the following information):**
 - Garbage Collection Card version: [e.g. 1.15.1]
 - Browser: Tested on Chrome and Safari
 - Browser language: English
 - Home Assistant: Core=2023.12.4, Supervisor=2023.12.0, Frontend=20231208.2

**Additional context**

**Comment by wilsto** [comment]
Hi @rpanachi , can you provide your yaml configuration card ? Thank you :)

**Comment by wilsto** [comment]
in v2, a clearer warning message will be displayed
![image](https://github.com/user-attachments/assets/0fed316c-8cfd-4aa5-bd02-d1927f1407e9)
